import type { Metadata } from 'next';
import { Lato, Inter } from 'next/font/google';
import './globals.scss';
import { cn } from '@/utils/cn';
import { Header } from '@/components/Header';
import { PageWrapper } from '@/components/PageWrapper';
import { Footer } from '@/components/Footer';
import Template from './template';

const lato = Lato({ subsets: ['latin'], weight: ['300', '400', '700'] });
const inter = Inter({ subsets: ['latin'], weight: ['300', '400', '700'] });

export const metadata: Metadata = {
  title: 'Ítalo Covas',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={cn(
          'flex h-full w-full items-center justify-center bg-[#151515]',
          inter.className
        )}
      >
        <PageWrapper>
          <Header />
          {children}
          <Footer />
        </PageWrapper>
      </body>
    </html>
  );
}
